<?php

return [
    // 'about' => 'Persian Classic Product is Lorem ipsum dolor, sit amet consectetur adipisicing elit. Delectus temporibus possimus rem! Asperiores dolor eaque eum odio, officiis nam delectus ea optio enim assumenda expedita, magni odit consequuntur repudiandae. Vitae!',
    'about' => 'Negin Tejarat Persia Company started its activity in 2012 by taking advantage of the 10-year experience of its founders and benefiting from a young and efficient scientific and technical staff. At first, its mission was to create a distribution team in the capital of Iran (Tehran) with the aim of distributing food products. At that time, the best available brands were included in the company\'s product rank. Due to the experience gained in the field of distribution of food products, from 2021, in cooperation with Moshirpour Company, which is an Iranian product distribution company in Italy, the foreign trade department of the company was also activated.',
    'about_2' => 'Now the main activity of the company is based on purchasing Iranian food products from the best domestic companies and distributing these products to food product distributors active in the international area such as European countries. Every year, this company continuously evaluates its performance by collecting market information and data, and with this process, it has succeeded in gaining the trust and satisfaction of customers on the one hand and foreign suppliers on the other hand, and for this reason, today the company has become one of the first choices of prominent foreign companies.',
    'biography' => 'Mahdi Rashvand Avaei was PhD graduated from School of Agriculture, Forestry, Food and Environmental Science, University of Basilicata. He is expert in food engineering and he published several scientific papers in the high qualified journal. During the master period he worked on the qualification and discrimination of the edibles oils such as olive oil using spectroscopy and data mining methods. Also, during the PhD course he investigated the modified atmosphere packaging (MAP) to enhance the shelf life of the fresh fruits and vegetables. Currently he is the expert and business man of the Negin Persia Company and who can answer to the consumer’s question. In the following you can find his contact details.',
    'address_1' => 'Headquarter:N.96, Azimie district, Karaj city, Alborz province, Iran',
    'address_2' => 'Italy branch: N.33, Via Vescovado, Potenza city,Basilicata Province, Italy',

];
